### ISSUE TITLE
Why in the f* do tasks that return [], 0, None all serialize to 0 in the database.

### ISSUE THREAD

**Issue by MadcowD** [django-q2/django-q2#106]
It's not a picklefield issue because picklefield.fields.dbsafe_encode([], 0, ...) all give different values..

Not sure if this was an issue with origianl django Q but its pretty glaring, for example, result(wait=-1) actually just sits there & waits if the "truth" value of the result is False rather than if it is None..

**Comment by GDay** [comment]
Thanks for creating the issue. 

> Why in the f* do tasks that return [], 0, None all serialize to 0 in the database

The title is actually not correct, it does store the correct value in the database:
```
>>> task = Task.objects.get(id="0b86cb58d30c422c9cbdf3a2f9324665")
>>> task
<Task: california-pluto-kentucky-uranus>
>>> task.result
[]
```
However, the `result(wait=-1)` only checks if the result is truthy, which `0`, `[]`, etc are not, so it will wait indefinitely.

It's indeed very interesting that this has not come up earlier (or I haven't seen it in the original repo). I have created a simple fix here: https://github.com/django-q2/django-q2/pull/107 That solves your issue, but doesn't solve the issue for people who are expecting a `None` back from the task.

I don't have much time at the minute, but will tackle this later this week. I think I will just check for if the task has stopped, instead of only checking for the result. Also need to write an extra testcase for this.

**Comment by MadcowD** [comment]
We were actually getting task.result = 0, let me  find a working example of this.

**Comment by GDay** [comment]
Fixed through that PR. Will create a new release tomorrow. 
Only thing to look out for is not returning `None` from the function, because that still creates an infinite loop. There isn't a clear indicator at the moment on when a task is fully processed (except for the result field), so that's a little harder to do without making massive changes. I have added a warning to the docs.

I could replicate the `result = 0` situation. It seems to work fine based on my test case: https://github.com/django-q2/django-q2/blob/f59c315c96b6851d8f35107e5d3a628b437cbf59/django_q/tests/test_cluster.py#L144-L165
