### ISSUE TITLE
Feature Request: set own id for task.

### ISSUE THREAD

**Issue by richard-infai** [django-q2/django-q2#112]
Currently the id is created in tasks.py

```python
    tag = uuid()
    # build the task package
    task = {
        "id": tag[1],
        "name": keywords.pop("task_name", None)
        or q_options.pop("task_name", None)
        or tag[0],
        "func": func,
        "args": args,
    }
```

For me it would be easier to set the task id like:

```python
    tag = uuid()
    # build the task package
    task = {
        "id": kewords.get("id", None) or tag[1],
        "name": keywords.pop("task_name", None)
        or q_options.pop("task_name", None)
        or tag[0],
        "func": func,
        "args": args,
    }
```

Is it possible to have this?

**Comment by GDay** [comment]
Thanks for the suggestion. Could you elaborate on the usecase for this a bit more? 
I am a little hesitant about implementing this. The id should always be unique as it's used to lookup the task in the database. We can be fairly certain that a normal uuid is unique. By implementing this, we would be shifting that responsibility to the developer.

**Comment by richard-infai** [comment]
My problem is: that i want to track the status in my own database (also the signals).
Now i have a timing problem. The signal from the queue can be faster then the update of database entry with the queue id.
If i can set the id by myself, the entry in the database will be there and i can easy update it.

**Comment by GDay** [comment]
Oh, interesting use case. Thanks for elaborating. I will think about it. 

For now, I think you should be able to get away with setting the `task_name` instead. https://django-q2.readthedocs.io/en/master/tasks.html#task-name

You should be able to get tasks with that as well. For example:
```
task_name = "test1123"
async_task(do_something, 1, task_name=task_name)
Task.objects.get(name=task_name)
```

Just make sure that the `task_name` is a maximum of 100 characters, is unique, and is preferably not 32 characters. The database does not check on that, so you will have to do that yourself.

**Comment by richard-infai** [comment]
Question: Why are these limitations, what is the source of this.
> maximum of 100 characters, is unique, and is preferably not exactly 32 character

**Comment by GDay** [comment]
The `name` field in the Task model has a `max_length` of 100 characters. It needs to be unique, because if it's not, you won't be able to get the correct task (it will likely error because there would be multiple tasks with the same name). The `name` field doesn't check on uniqueness, unlike the `id` field. 

A normal `id` is always 32 characters long. You could end up with a conflict with a generated id if you make them 32 characters long. It first tries to fetch the result based on id and then on name. See this part:
https://github.com/django-q2/django-q2/blob/68af2ae13e6eefbfa740e6730b8ea9ffdb7d6ad2/django_q/models.py#L43-L48
