### ISSUE TITLE
RFC: Custom Hooks

### ISSUE THREAD

**Issue by SchrodingersGat** [django-q2/django-q2#123]
Over on the [InvenTree](https://github.com/inventree/inventree) project we make heavy use of django-q2 (previously django-q). It's fantastic!

I have a tricky problem I am trying to address, not sure if there is a way to do this already in django-q...

Basically, we support custom plugins for InvenTree. Plugins can be installed (via the frontend web interface) without restarting the server.

Background tasks (via django-q) can make use of the plugins. However if a new plugin has just been installed, the django-q worker process(es) won't have access to the plugin code, without either:

- Manually calling the code to re-load and re-register all the plugins, in each django-q worker process
- Fully restarting the django-q worker process (and thus reloading the plugins)

What we need to do, is whenever a new plugin is installed (or uninstalled) via the front-end, cause *all* django-q worker processes to reload the plugins, to ensure that the background and foreground workers are all running the same codebase.

I can think of two potential approaches, I'd like input on whether they are either already possible, or feasible with some tweaks.

### Reload Workers

Can I send a signal to *all* running django-q worker services (independent of whether they are running on bare metal, docker, etc) to restart the process, and thus run the re-load plugins code? This would be the simplest approach, if I can simply send a signal (or similar) from the frontend web worker and restart all background workers

### Pre-Task Hook

Another approach would be to check (before every task) if the plugins need to be reloaded. So, some sort of "hook" which can be called before any task is actually performed by each worker. In this fashion, each individual worker would be responsible for reloading itself, if it detects that the plugin state has been adjusted.

------------

Thanks in advance for any input. Love the project, thanks for the fork :)

**Comment by GDay** [comment]
Cool to see django-q2 being used in a big project! Thanks for using it!

Interesting usecase. This is actually a bit of a tricky one. The biggest issue here is that reloading the workers doesn't seem to be enough. I have just tested it by forcing a task to crash and after running it, changing the task manually to let it pass. The worker crashed and reincarnated (it just spins up a new worker), but it didn't pick up any code changes. It kept crashing on the same part (which didn't exist anymore after my change). FWIW, I was using Docker.

> Manually calling the code to re-load and re-register all the plugins, in each django-q worker process

I haven't looked into the IvenTree source code and I am not sure how you guys are doing that, but there is [a signal that can be triggered before a task is ran](https://django-q2.readthedocs.io/en/master/signals.html#before-executing-a-task). Again, I don't think this would actually work, since the the code doesn't seem to be getting updated.

I think the only possible solution here would be to gracefully kill the entire django-q(2) cluster (including scheduler, monitor etc) and then start it again. With some modifications this can likely be implemented as a custom function that can be called (which would put something in the queue to restart the cluster).

**Comment by SchrodingersGat** [comment]
@GDay thanks for the response. Is there a way to kill and restart the cluster from within the code itself?

I'm actually trying a different implementation - see https://github.com/inventree/InvenTree/pull/5624

The approach here is to check a stored hash of the plugin libraries, and reload the plugins when the hash changes. This seems to work well and reach running worker process is restarted only when it needs to run plugin code.

**Comment by GDay** [comment]
> Is there a way to kill and restart the cluster from within the code itself?

Unfortunately, there is not right now.

> This seems to work well and reach running worker process is restarted only when it needs to run plugin code

This looks like a good approach. I am a bit surprised that this actually worked, since the code didn't seem to update for me when the cluster was already running.

**Comment by SchrodingersGat** [comment]
> Unfortunately, there is not right now.

Fair enough, this would be very useful though. An auto reload feature like Django runserver would be great!

I'll close this out as I have a working solution for now. Thanks for the comments
