### ISSUE TITLE
Multiple clusters concurrency

### ISSUE THREAD

**Issue by masb3** [django-q2/django-q2#171]
From the docs it is stated that I can have multiple clusters on multiple machines, working on the same queue. But I'm missing understanding from architecture https://django-q2.readthedocs.io/en/latest/architecture.html how multiple Pushers are synchronized, so they don't push same task to different task queues. Maybe it is worth to improve doc or can you explain here?

**Comment by GDay** [comment]
The pusher gets the task from the broker. We make sure that it either gets popped from the broker, so that it won't exist anymore after the pusher got it, or we lock the task to a certain time so that other pushers can't take it. 

In the case of the ORM for example, we lock the task:
https://github.com/django-q2/django-q2/blob/7add68f7709856f875bf145d59374adc80112009/django_q/brokers/orm.py#L66-L83

Let me know if you have questions.

**Comment by masb3** [comment]
> The pusher gets the task from the broker. We make sure that it either gets popped from the broker, so that it won't exist anymore after the pusher got it, or we lock the task to a certain time so that other pushers can't take it.
> 
> In the case of the ORM for example, we lock the task:
> 
> https://github.com/django-q2/django-q2/blob/7add68f7709856f875bf145d59374adc80112009/django_q/brokers/orm.py#L66-L83
> 
> Let me know if you have questions.

Thank you for reply. That is pretty clear for me now.
