### ISSUE TITLE
Cannot install latest version on Ubuntu 20.04

### ISSUE THREAD

**Issue by baxeico** [django-q2/django-q2#83]
Hi,
I cannot install latest version (currently 1.4.11) on Ubuntu 20.04. Python version from Ubuntu repositories is 3.8.10, but django-q2 [requires at least Python 3.8.14](https://github.com/django-q2/django-q2/blob/master/pyproject.toml#L47).

Can you please check if this is an hard requirement? Curiously, version django-q2==1.4.0 can be installed on Python 3.8.10.

Thank you very much for your help and keep up with the good work!

**Comment by GDay** [comment]
Yeah, that's not ideal. Django-q2 should work under any 3.8.x version, so that requirement isn't correct.

You can ignore the requirement for now, by using the `--ignore-requires-python` flag (https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-ignore-requires-python) when installing. 

Will fix this with the next version. Thanks for raising this issue.

**Comment by GDay** [comment]
This should be fixed under version 1.5.1. Thanks again for letting me know!

https://github.com/django-q2/django-q2/blob/322a53f06d1090521b16d97571b32af92a3d91d6/pyproject.toml#L46-L47
